/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.practice.KafkaProducerConsumer;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

import com.util.KafkaUtil;

@SpringBootApplication
@ComponentScan(basePackages = { "com.controller", "com.util", "com.service" })
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
